version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "7777:7777"
  
  frontend:
    build:
      context: ./agent-ui
      dockerfile: Dockerfile.ui
    ports:
      - "3000:3000"
    depends_on:
      - backend
